twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        app_version: '%env(APP_VERSION)%'
        site_title: '%env(SITE_TITLE)%'